<?php

namespace Drupal\casella_custom\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

class DateConfigurationForm extends ConfigFormBase {

  /**
   * @return array|void
   */
  protected function getEditableConfigNames() {
    return ['casella_custom.test'];
  }

  /**
   * @return string|void
   */
  public function getFormId() {
    return 'date_configuration_form';
  }

  /**
   * @param array $form
   * @param FormStateInterface $form_state
   * @return array
   */
  public function buildForm(array $form, FormStateInterface $form_state) {
    $config = $this->config( 'casella_custom.test' );
    return parent::buildForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  /**
   * @param array $form
   * @param FormStateInterface $form_state
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
  }

}
