pc.settings:
  type: config_object
  label: PHP console settings
  mapping:
    password_enabled:
      type: boolean
      label: Recursion limit for actions
    password:
      type: string
      label: Password for client authorization
    remote_php_execution:
      type: boolean
      label: Enable remote PHP code execution
    ips:
      type: string
      label: Allowed IP masks
    track_errors:
      type: boolean
      label: Track PHP errors
    dumper_maximum_depth:
      type: integer
      label: Maximum dumper depth
    debug_info:
      type: mapping
      label: Debug information
      mapping:
        server:
          type: boolean
          label: Server
        session:
          type: boolean
          label: Session
        cookie:
          type: boolean
          label: Cookie
        post:
          type: boolean
          label: Post
        get:
          type: boolean
          label: Get
        logged_user:
          type: boolean
          label: Logged user
        route:
          type: boolean
          label: Current route
        forms:
          type: boolean
          label: Forms
        memory_usage:
          type: boolean
          label: Memory usage
        peak_memory_usage:
          type: boolean
          label: Peak memory usage
        execution_time:
          type: boolean
          label: Execution time
        db_queries:
          type: boolean
          label: DB queries
        watchdog:
          type: boolean
          label: Watchdog messages
        emails:
          type: boolean
          label: Emails
