<?php

namespace Drupal\casella_custom\Controller;

use Drupal\Core\Controller\ControllerBase;
use Drupal\casella_custom\ConditionalDate;
use Symfony\Component\DependencyInjection\ContainerInterface;

class CasellaCustomController extends ControllerBase {

  /**
   * @var ConditionalDate $conditionalDate
   */
  protected $conditionalDate;

  /**
   * CasellaCustomController constructor.
   * @param ConditionalDate $conditionalDate
   */
  public function __construct(ConditionalDate $conditionalDate) {
    $this->conditionalDate = $conditionalDate; // injected service
  }

  public function main() {
    $service = \Drupal::service('casella_custom.conditional_date');

    return [
      '#markup' => $this->conditionalDate->getConditionalDate()
    ];

  }

  /**
   * @param ContainerInterface $container
   * @return CasellaCustomController|ControllerBase
   */
  public static function create(ContainerInterface $container) {
    return new static( $container->get('casella_custom.conditional_date') );
    //return parent::create($container); // TODO: Change the autogenerated stub
  }
}
